In [1]:
import numpy as np
other_array = np.array([[[12,13],[14,3],[11,10]]])
print(other_array)

[[[12 13]
  [14  3]
  [11 10]]]


In [2]:
import numpy as np

In [8]:

other_array = np.array([[12,13,45],[31,53,87]])
new_array = np.array([[98,54,45],[4,7,6]])
result = other_array + new_array
print(result)
print(result.shape)

[[110  67  90]
 [ 35  60  93]]
(2, 3)


In [23]:
thrid_array =np.array([[[1,2],[3,4],[5,6]],
               [[7,8],[9,7],[6,4]]])
print(thrid_array)
print(thrid_array.shape)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 7]
  [6 4]]]
(2, 3, 2)


In [32]:
import numpy as np
array_of_integers = np.array([[[[1,2,3],[4,5,6],[22,33,44],[55,77,99]]]])
sample_2D_integers = np.array([1,22,3,4,5,6,7,8,9,0])
print("Dimensions of 'array_of_integers' = ", array_of_integers.ndim)
print("Dimensions of 'sample_2D_integers' =", sample_2D_integers.ndim)
print(f"The total number of elements'array_of_integers' = {array_of_integers.size}")
print(f"The total number of elements'sample_2D_integers' = {sample_2D_integers.size}")

Dimensions of 'array_of_integers' =  4
Dimensions of 'sample_2D_integers' = 1
The total number of elements'array_of_integers' = 12
The total number of elements'sample_2D_integers' = 10


In [39]:
import numpy as np
my_array = np.array([1,2,3,4,5])
mny_array = np.array([1,2,3,4,'abc'])
mky_array = np.array(['abc','dgd','dgw'])
print(my_array.dtype)                    
print(mny_array.dtype)
print(mky_array.dtype)

int32
<U11
<U3


In [42]:
import numpy as np
arravali = np.array([2,3,4])
print(arravali)
print(arravali.dtype)
arravali_ = arravali.astype('float64')
print(arravali)
print(arravali.dtype)

[2 3 4]
int32
[2 3 4]
int32


In [60]:
import numpy as np
import random
arravali = np.array(np.random.randint([[10,45],[9,6]]))
print(f"the defined array is\n {arravali}")
print(f"\n the shape of the array is {arravali.shape}")

the defined array is
 [[ 7 41]
 [ 3  3]]

 the shape of the array is (2, 2)


In [3]:
import numpy as np
import random
random_cohort= np.array(np.random.randint(10,45,(3,1,2)))
print(f"the defined array is\n {random_cohort}")
print(f"\n the shape of the array is {random_cohort.shape}")
new_shape = (4,-2,5)
reshape_random_cohort= np.array(np.random.randint(10,45,(3,1,2)))
print(f"the defined array is\n {reshape_random_cohort}")
print(f"\n the shape of the array is {reshape_random_cohort.reshape}")
new_shape = (4,-2,5)
reshape_random_cohort= np.array(np.random.randint(10,45,(3,1,2)))
print(f"the defined array is\n {reshape_random_cohort}")
print(f"\n the shape of the array is {reshape_random_cohort.flatten()}")


the defined array is
 [[[15 42]]

 [[13 29]]

 [[42 42]]]

 the shape of the array is (3, 1, 2)
the defined array is
 [[[29 14]]

 [[21 23]]

 [[15 37]]]

 the shape of the array is <built-in method reshape of numpy.ndarray object at 0x0000021A608CBB10>
the defined array is
 [[[20 27]]

 [[18 25]]

 [[38 12]]]

 the shape of the array is [20 27 18 25 38 12]


In [8]:
import numpy as np
a = np.random.randint(30,80,(2,4,5))
a = np.insert(a,1,80,axis = 0)

print(a)
print(a.shape)

[[[66 30 59 51 31]
  [56 53 30 73 65]
  [67 71 76 43 51]
  [36 41 46 73 32]]

 [[80 80 80 80 80]
  [80 80 80 80 80]
  [80 80 80 80 80]
  [80 80 80 80 80]]

 [[41 57 72 54 43]
  [38 47 31 75 76]
  [56 62 46 73 53]
  [74 51 62 61 35]]]
(3, 4, 5)


In [15]:
import numpy as np
a = np.random.randint(2,6,(2,1,3))
b = np.random.randint(2,4,(2,1,2))
print(b.shape)
print(b)


(2, 1, 2)
[[[3 3]]

 [[2 2]]]


In [16]:
import numpy as np
alma_array = np.random.randint(10,60,(3,3,5))
print(alma_array)
print(alma_array.shape)
alma_array = np.delete(alma_array,(0,3),axis =2)
print(alma_array)

[[[13 57 35 19 53]
  [20 33 58 19 19]
  [41 28 43 35 57]]

 [[20 16 55 50 59]
  [39 34 17 29 42]
  [23 44 57 39 10]]

 [[13 52 24 13 11]
  [10 31 52 28 48]
  [10 38 29 11 29]]]
(3, 3, 5)
[[[57 35 53]
  [33 58 19]
  [28 43 57]]

 [[16 55 59]
  [34 17 42]
  [44 57 10]]

 [[52 24 11]
  [31 52 48]
  [38 29 29]]]


In [29]:
import numpy as np
a = np.random.randint(10,20,(2,3,4))
print(a)
print(a.shape)
np.unique(a)
np.append(a,50)
np.delete(a,(0),axis = 0)

[[[17 13 19 10]
  [12 15 15 10]
  [16 19 17 10]]

 [[13 16 14 17]
  [13 15 18 16]
  [11 12 14 14]]]
(2, 3, 4)


array([[[13, 16, 14, 17],
        [13, 15, 18, 16],
        [11, 12, 14, 14]]])

In [34]:
import numpy
my_list = [[12,34,56],[55,76,54],[54,85,44]]
matrix = numpy.array(my_list)
print(matrix)
# res = matrix [: , :]
# print(res)
res = matrix [0 :3 , 0:3]
print(res)

[[12 34 56]
 [55 76 54]
 [54 85 44]]
[[12 34 56]
 [55 76 54]
 [54 85 44]]


In [17]:
import numpy as np
m = int(input("Enter row size"))
n = int(input("Enter column size"))
matrix = np.ndarray(shape = (m,n),dtype = int)
print("Enter %d elements of %dx%d matrix :" %(m*n,m,n))
    zfor i in range(m):
    for j in range(n):
        matrix [i] [j] = int(input())
print(" %dx%d matrix :" %(m,n))
print(matrix)

Enter row size 3
Enter column size 2


Enter 6 elements of 3x2 matrix :


 4
 6
 5
 8
 9
 2


 3x2 matrix :
[[4 6]
 [5 8]
 [9 2]]


In [45]:
import numpy
arr = numpy.ndarray(shape = (2.8,2,2) , dtype = float)
val = 1
x = arr.shape[0]
y = arr.shape[1]
z = arr.shape[2]
for i in range(x):
    for j in range(y):
        for k in range(z):
            arr [i] [j] [k] = val
            val = val + 1
print("array elements")
print(arr)

array elements
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
